spring:
  application:
    name: hhplus-architecture

  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: 1234
    hikari:
      connection-timeout: 20000
      auto-commit: false
      Isolation: TRANSACTION_READ_COMMITTED
      maximum-pool-size: 5
      minimum-pool-size: 1


    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          provider_disables_autocommit: false
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        transaction: DEBUG
      springframework:
        web: DEBUG